### PR TITLE
Add JAAS Authentication Modules for KRB5, LDAP , etc

### PR DESCRIPTION
**Pull request by prateek05**
First Stab

### CODE REVIEW

**Comment by prateek05** [comment]
@s-u First Attempt... Verified KRB5 and PAM

**Comment by s-u** [comment]
Thanks, I have committed something based on this but simplified and a bit more generic to allow arbitrary modules. Since the options are simple properties (and thus are not actually loaded anyway) there is no point in using them in the code itself. To enable JAAS you have to specify `-jaas jaas.conf` and you can use `-krb5conf /etc/krb5.conf`, but generally you can always set any additional properties using `-D` in the Java invocation.

Please test if the committed version works in your setting.
Thanks,
Simon

**Comment by prateek05** [comment]
Yes it works.
Test module=KerberosModule:
AUTH/KerberosModule: 1423705246463 user='pb763a', rcloud.exec, OK
Test module=PAM:
AUTH/PAM: 1423705284892 user='baranwal', rcloud.exec, OK
Test with no module in request:
AUTH/PAM: 1423706279421 user='baranwal', rcloud.exec, OK
Test Legacy:
PAM: 1423705292244 user='baranwal', rcloud.exec, OK

**Comment by s-u** [comment]
Great, thanks!

**Pull request closed without merging**
